"""The data tier the 27 services depend on.

Until this existed the k8s manifests deployed the application tier alone. The
ConfigMap named `postgres.smartseason.svc.cluster.local`, `redis` and `kafka:9092`,
and nothing in the repository created any of them, so `kubectl apply -f k8s/`
produced 29 deployments that crash-looped on an unresolvable database host.

`check-k8s-env.py` could not catch it and still cannot: it verifies that every
variable is *provided* and that every Secret and ConfigMap key *exists*. Whether the
hostname in a value is backed by a running workload is a different question, and a
green gate answered the first one convincingly enough to hide the second.

Three deliberate limits, stated here because they are the ceiling of this tier:

  - **One replica each.** Postgres, Redis and Redpanda are single pods. That makes
    the data layer a single point of failure and caps the whole platform's
    availability at one node's. It is honest for a first cluster deploy and must be
    replaced by managed services, or by an operator that runs real replication,
    before this carries production traffic.
  - **Object storage is MinIO, single node.** S3-compatible on purpose: swapping to real S3,
    Spaces or R2 later is a config change, not a rewrite. One replica means it is not durable
    against node loss - that is what a managed bucket is for.
  - **No read replicas**, so every read still lands on the primary. The services
    already annotate 131 transactions `readOnly = true`, so the routing hook exists;
    nothing routes yet.
  - **PgBouncer over-subscribes on purpose.** See the arithmetic in the manifest.

The PgBouncer configuration is read from `infra/docker/pgbouncer/` at generation
time rather than copied here. Two hand-maintained copies of a connection-pooler
config drift, and the failure when they do is a pool size that is correct locally
and wrong in the cluster.
"""

DATA_LAYER = '''---
# Generated by tools/gen_k8s.py - edit tools/tpl_data.py, not this file.
#
# The data tier: Postgres behind PgBouncer, Redis, and Redpanda speaking the Kafka
# protocol. Apply this before the service manifests; they have no retry budget for a
# database that does not exist yet, and 29 deployments crash-looping is a slow way to
# discover an ordering mistake.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: {ns}
data:
  # One database per service, generated from the catalogue. Deriving these names by
  # string surgery on the service name is what put `device-registry_db` and
  # `telemetry-ingest_db` into the manifests while the databases were really called
  # `device_db` and `telemetry_db`.
  init-databases.sh: |
    #!/bin/sh
    set -eu
{init_sql}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {ns}
  labels:
    app: postgres
spec:
  # Headless. There is one database pod and nothing should load-balance across
  # database replicas as though they were interchangeable.
  clusterIP: None
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {ns}
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        # The alpine image runs as uid 70; the mounted volume must be group-writable
        # by it or initdb fails on a permission error that reads like corruption.
        fsGroup: 70
      containers:
        - name: postgres
          image: postgres:16-alpine
          # PgBouncer is allowed to ask for more connections than this in the worst
          # case - see the pool arithmetic below - so this is the backstop that turns
          # over-subscription into a refused connection rather than an exhausted
          # server. Raise it and default_pool_size together, never separately.
          args: ["postgres", "-c", "max_connections=400"]
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: smartseason-config
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smartseason-secrets
                  key: DB_PASSWORD
            # A mounted volume always contains lost+found, and Postgres refuses to
            # initialise into a directory that is not empty. Putting the cluster in a
            # subdirectory is the standard way round it.
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER"]
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER"]
            initialDelaySeconds: 45
            periodSeconds: 20
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              memory: 2Gi
      volumes:
        - name: init
          configMap:
            name: postgres-init
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: {ns}
data:
  # Read verbatim from infra/docker/pgbouncer/ at generation time. `host=postgres`
  # already resolves in this namespace, so the file needs no cluster-specific edit -
  # which is the point of not keeping a second copy.
  pgbouncer.ini: |
{pgbouncer_ini}
  entrypoint.sh: |
{pgbouncer_entrypoint}
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: {ns}
  labels:
    app: pgbouncer
spec:
  selector:
    app: pgbouncer
  ports:
    - name: pgbouncer
      port: 6432
      targetPort: 6432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: {ns}
  labels:
    app: pgbouncer
  annotations:
    # check-k8s-scaling.py requires an autoscaler on every Deployment. A connection
    # pooler is the one place that rule is wrong: scaling it on CPU multiplies the
    # server-side connections it opens, so the response to load would be to consume
    # more of the resource that is already scarce. Pinned instead, with the pool
    # arithmetic below sized for exactly this replica count.
    smartseason.io/no-hpa: >-
      A pooler must not autoscale: each replica opens its own server-side pools, so
      scaling out consumes the Postgres connection budget rather than relieving it.
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgbouncer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer:v1.23.1-p2
          # The ConfigMap mount is read-only and the entrypoint writes userlist.txt
          # next to the ini, so /etc/pgbouncer is a writable emptyDir and the config
          # is copied in. The upstream entrypoint then runs unchanged.
          command: ["sh", "-c", "cp /config/pgbouncer.ini /etc/pgbouncer/ && exec sh /config/entrypoint.sh"]
          ports:
            - name: pgbouncer
              containerPort: 6432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: smartseason-config
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smartseason-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: config
              mountPath: /config
            - name: runtime
              mountPath: /etc/pgbouncer
          readinessProbe:
            tcpSocket:
              port: 6432
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: pgbouncer-config
            defaultMode: 0755
        - name: runtime
          emptyDir: {{}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pgbouncer
  namespace: {ns}
spec:
  # One of two, so a node drain can never take both and leave 27 services without a
  # route to the database. Below the replica count, or the drain blocks for ever.
  minAvailable: 1
  selector:
    matchLabels:
      app: pgbouncer
---
apiVersion: v1
kind: Service
metadata:
  name: objectstore
  namespace: {ns}
  labels:
    app: objectstore
spec:
  clusterIP: None
  selector:
    app: objectstore
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: objectstore
  namespace: {ns}
spec:
  serviceName: objectstore
  replicas: 1
  selector:
    matchLabels:
      app: objectstore
  template:
    metadata:
      labels:
        app: objectstore
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: minio
          image: minio/minio:RELEASE.2024-10-13T13-34-11Z
          args: ["server", "/data", "--console-address", ":9001"]
          ports:
            - name: s3
              containerPort: 9000
            - name: console
              containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: smartseason-secrets
                  key: S3_ACCESS_KEY
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smartseason-secrets
                  key: S3_SECRET_KEY
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {ns}
  labels:
    app: redis
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: {ns}
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: redis
          image: redis:7-alpine
          # Rate-limit buckets and cached row counts both survive a restart with
          # appendonly on. Neither is authoritative - the limiter fails open and the
          # count falls back to the database - so this is a convenience, not a
          # durability guarantee.
          args: ["redis-server", "--appendonly", "yes"]
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  # Named `kafka` because that is what KAFKA_BOOTSTRAP_SERVERS already says and what
  # 27 services are configured to reach. Redpanda speaks the Kafka protocol; the name
  # describes the contract, not the implementation.
  name: kafka
  namespace: {ns}
  labels:
    app: kafka
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: {ns}
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        fsGroup: 101
      containers:
        - name: redpanda
          image: redpandadata/redpanda:v24.2.8
          args:
            - redpanda
            - start
            - --smp=1
            - --overprovisioned
            - --node-id=0
            - --kafka-addr=PLAINTEXT://0.0.0.0:9092
            # Must be the Service name: this is the address brokers hand back to
            # clients after the bootstrap call, so a wrong value here produces a
            # connection that succeeds and then times out on the first produce.
            - --advertise-kafka-addr=PLAINTEXT://kafka.{ns}.svc.cluster.local:9092
          ports:
            - name: kafka
              containerPort: 9092
          volumeMounts:
            - name: data
              mountPath: /var/lib/redpanda/data
          readinessProbe:
            exec:
              command: ["sh", "-c", "rpk cluster health | grep -q 'Healthy:.*true'"]
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              memory: 1Gi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
'''


def build(namespace, services, pgbouncer_ini, pgbouncer_entrypoint):
    """Renders the data tier.

    `services` are catalogue entries; their `db` key is used directly rather than
    derived from the service name, because two of the twenty-seven do not match.
    """
    lines = []
    for spec in services:
        db = spec["db"]
        lines.append(
            f'    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" '
            f"-c \"CREATE DATABASE {db};\""
        )
    init_sql = "\n".join(lines)

    def indent(text, spaces=4):
        pad = " " * spaces
        return "\n".join(pad + line if line.strip() else "" for line in text.rstrip().split("\n"))

    return DATA_LAYER.format(
        ns=namespace,
        init_sql=init_sql,
        pgbouncer_ini=indent(pgbouncer_ini),
        pgbouncer_entrypoint=indent(pgbouncer_entrypoint),
    )
