#!/usr/bin/env bash
#
# One command to a running, populated SmartSeason demo on a laptop.
#
#   scripts/demo.sh            build what is missing or changed, start, seed, print where to go
#   scripts/demo.sh reset      throw the demo volumes away and start from empty
#   scripts/demo.sh down       stop everything (data is kept)
#   scripts/demo.sh seed       only (re)run the seed against a running stack
#   scripts/demo.sh status     what is up, and how much memory it takes
#   scripts/demo.sh check      open every web screen as every role; report empty or broken ones
#
# Runs 20 of the 26 services (measured 7.4 GiB across the 27 containers) (the ones the web screens call) plus Postgres, PgBouncer, Redis,
# Redpanda, MinIO, the gateway and the web app. See docker-compose.demo.yml.
set -euo pipefail
cd "$(dirname "$0")/.."

ENV_FILE="${ENV_FILE:-.env.demo}"

# The services the demo runs. DEMO_SERVICES (below) is the same list as web slugs.
SERVICES=(identity farm season agronomy weather
          workforce attendance task fraud
          catalog pricing order inventory logistics
          payment ledger payout
          traceability media audit)

say() { printf '\n\033[1m%s\033[0m\n' "$*"; }

# Throwaway secrets, generated once per checkout and never committed (.env.* is gitignored).
make_env() {
  local pass
  pass="$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-20)"
  cat > "$ENV_FILE" <<EOF
# SmartSeason DEMO environment, generated by scripts/demo.sh. Every value is a throwaway for a
# laptop demo: delete this file to get new ones, and never reuse any of them anywhere else.
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$(openssl rand -hex 16)
# The role the services run as; row-level security applies to it. POSTGRES_* is Flyway-only.
APP_DB_USER=smartseason_app
APP_DB_PASSWORD=$(openssl rand -hex 16)
JWT_SECRET=$(openssl rand -hex 48)
JWT_ISSUER=smartseason-identity
S3_ACCESS_KEY=smartseason
S3_SECRET_KEY=$(openssl rand -hex 16)
EVENTS_ENABLED=true
LOG_LEVEL=INFO
DB_POOL_MAX=6

# Host ports (chosen not to clash with the other demo stacks on this machine).
WEB_PORT=13000
GATEWAY_PORT=18080
CORS_ALLOWED_ORIGINS=http://localhost:13000

# Demo conveniences. All three are off in .env.example and must stay off on a real deployment.
QUICK_SIGN_IN=true
QUICK_SIGN_IN_PASSWORD=$pass
EXPOSE_RESET_CODE=true
DEMO_PASSWORD=$pass
EOF
  chmod 600 "$ENV_FILE"
  echo "wrote $ENV_FILE with fresh throwaway secrets"
}
[ -f "$ENV_FILE" ] || make_env
# An .env.demo written before row-level security existed has no application-role password.
if ! grep -q '^APP_DB_PASSWORD=' "$ENV_FILE"; then
  printf 'APP_DB_USER=smartseason_app\nAPP_DB_PASSWORD=%s\n' "$(openssl rand -hex 16)" >> "$ENV_FILE"
  echo "added an application database role password to $ENV_FILE"
fi

set -a; . "./$ENV_FILE"; set +a
DEMO_SERVICES="$(IFS=,; echo "${SERVICES[*]}")"
export DEMO_SERVICES
export GATEWAY="http://localhost:${GATEWAY_PORT:-18080}"

DC="docker compose --env-file $ENV_FILE -f docker-compose.yml -f docker-compose.demo.yml"
STATE_DIR=".demo"
mkdir -p "$STATE_DIR"

# A digest of everything that goes into an image, so a source change rebuilds it and nothing
# else does. (File times would not do: regenerating the tree touches every file.)
src_hash() {
  local dir="$1"
  find "$dir" -type f -not -path '*/target/*' -not -path '*/node_modules/*' -not -path '*/.next/*' \
    -print0 | sort -z | xargs -0 sha256sum | sha256sum | cut -d' ' -f1
}

build_one() {
  local name="$1" dir="$2" image="$3" h
  h="$(src_hash "$dir")"
  if [ -n "$(docker images -q "$image")" ] && [ "$(cat "$STATE_DIR/$name.hash" 2>/dev/null)" = "$h" ]; then
    return 0
  fi
  say "Building $name"
  $DC build "$name"
  echo "$h" > "$STATE_DIR/$name.hash"
}

build_missing() {
  # One at a time: Maven for twenty images at once runs a small machine out of memory.
  for s in "${SERVICES[@]}"; do
    build_one "$s-service" "services/$s-service" "smartseason-$s-service:latest"
  done
  build_one api-gateway apps/api-gateway smartseason-api-gateway:latest
  build_one web apps/web smartseason-web:latest
}

up_services() {
  local list=(postgres pgbouncer redis redpanda objectstore api-gateway web)
  for s in "${SERVICES[@]}"; do list+=("$s-service"); done
  echo "${list[@]}"
}

case "${1:-up}" in
  down)   $DC --profile all down; exit 0 ;;
  reset)  $DC --profile all down -v; shift || true ;;
  status) $DC ps; docker stats --no-stream --format '{{.Name}} {{.MemUsage}}' | grep smartseason-demo | sort; exit 0 ;;
  seed)   python3 scripts/demo_seed.py; exit $? ;;
  check)  python3 scripts/demo_check.py; exit $? ;;
  up)     ;;
  *)      echo "usage: $0 [up|reset|down|seed|check|status]"; exit 2 ;;
esac

build_missing

say "Starting the stack (about 7.5 GiB, 5-6 minutes from empty)"
# Started in two waves: Spring Boot services starting together with the broker and database
# all compete for the same few cores and the slowest start times out its health check.
$DC up -d --no-build postgres redis redpanda objectstore
# The init script creates the application role only on an empty volume. Make sure it exists (and
# has this env file's password) on a volume that predates it, before PgBouncer and the services
# try to log in as it.
for i in $(seq 1 60); do
  $DC exec -T postgres pg_isready -U "$POSTGRES_USER" >/dev/null 2>&1 && break
  sleep 1
done
$DC exec -T postgres psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" \
    -v app_user="${APP_DB_USER:-smartseason_app}" -v app_pw="$APP_DB_PASSWORD" >/dev/null <<'SQL'
SELECT format('CREATE ROLE %I LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS NOREPLICATION', :'app_user', :'app_pw')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'app_user') \gexec
SELECT format('ALTER ROLE %I PASSWORD %L', :'app_user', :'app_pw') \gexec
SQL
$DC up -d --no-build pgbouncer
$DC up -d --no-build $(up_services)

say "Waiting for everything to report healthy"
bad=1
for i in $(seq 1 120); do
  bad=$($DC ps --format '{{.Name}} {{.Health}}' | grep -vc "healthy" || true)
  [ "$bad" = "0" ] && break
  sleep 5
done
[ "$bad" = "0" ] || { echo "not everything became healthy:"; $DC ps --format '{{.Name}} {{.Health}}' | grep -v healthy; exit 1; }

# The gateway keeps its circuit breakers open if it saw a backend down while they were starting.
$DC restart api-gateway >/dev/null
for i in $(seq 1 90); do
  [ "$(curl -s -o /dev/null -w '%{http_code}' "$GATEWAY/actuator/health")" = "200" ] && break
  sleep 2
done

say "Seeding demo data through the API"
python3 scripts/demo_seed.py

cat <<MSG

  SmartSeason is ready.

    Web app      http://localhost:${WEB_PORT:-13000}
    API gateway  http://localhost:${GATEWAY_PORT:-18080}

  The login page has a "Sign in as" picker for every role. To type a password instead,
  it is the same for all accounts:  ${DEMO_PASSWORD}

    demo@smartseason.local         ADMIN         everything
    farmer@smartseason.local       FARMER        reads all, moves no money
    manager@smartseason.local      MANAGER       today's work and the people doing it
    agronomist@smartseason.local   AGRONOMIST    crop advisor, scouting, weather
    store@smartseason.local        STOREKEEPER   stock and transport
    finance@smartseason.local      FINANCE       the only role that moves money
    buyer@smartseason.local        BUYER         orders, prices, deliveries
    amina@smartseason.local        WORKER        her own tasks only
    joseph@smartseason.local       WORKER        a second worker

  M-Pesa is simulated: nothing leaves this machine and no money moves.
  Six services are not running in the demo (devices, telemetry, automation, notification,
  search, analytics); their menus are hidden. Everything else is the real code.

MSG
